#!/bin/bash

T=tst_special_atts
#T=nccopy
VG=valgrind --leak-check=full
GDB=gdb --args
#ARGS=tst_comp.nc copy_of_tst_comp.nc

#L=/.libs

EXP=export LD_LIBRARY_PATH="/usr/local/lib"

CFLAGS=-gstabs+ -O0 -I.. -I../include -I. -I/usr/local/include -I/usr/include
LDFLAGS=../liblib/.libs/libnetcdf.a  -L/usr/local/lib -lhdf5_hl -lhdf5 -lz -lm -lcurl -lbz2

NCC=nccopy.c nciter.c chunkspec.c utils.c dimmap.c


all::
	${EXP} ; gcc -o ${T} ${CFLAGS} ${T}.c ${LDFLAGS}
#	${EXP} ; gcc -o ncc ${CFLAGS} ${NCC} ${LDFLAGS} ;\

t::
	${EXP} ; ./${T} ${ARGS}

g::
	${EXP} ; ${GDB} .${L}/${T} ${ARGS}

v::
	${EXP} ; ${VG} .${L}/${T} ${ARGS}
